<div class="nav">
    <ul class="nav-wrap">
        <li class="<?php echo $this->controller() =='default' ? 'active' : ''?>">
            <a href="<?php echo $this->url('default/index')?>">
                <span class="icon-wrap"><i class="icon-house"></i></span>
                <span class="text-wrap">首页</span>
            </a>
        </li>
        <li class="<?php echo $this->controller() == 'admin' ? 'active' : ''?>">
            <a href="<?php echo $this->url('admin/member-list')?>">
                <span class="icon-wrap"><i class="icon-report"></i></span>
                <span class="text-wrap">后台设置</span>
            </a>
            <ul class="<?php echo $this->controller() != 'admin' ? 'none' : ''?>">
                <li class="<?php echo preg_match("/member/i", $this->action()) ? 'active' : ''?>">
                    <a href="<?php echo $this->url('admin/member-list');?>">
                        <span class="hidden-sm">人员管理</span>
                    </a>
                </li>
            </ul>
        </li>
    </ul>
</div>
<span id="short-sidebar" class="short-menu-bar clearfix">
    <i class="icon-arrow-left-strong"></i>
</span>